# Generated by Django 5.0.2 on 2024-03-26 15:30

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rutaggeditem_rutag_testpost'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='blog.RuTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
