# Generated by Django 5.0.2 on 2024-03-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPost',
        ),
    ]
