# Generated by Django 5.0.2 on 2024-02-21 12:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое'),
        ),
    ]
