# Generated by Django 5.0.2 on 2024-02-21 12:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_text2_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descriptive',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
