# Generated by Django 5.0.2 on 2024-03-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_descriptive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',), 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
